In [2]:
import numpy as np

In [14]:
a = [   [ -1,2]   ,   [-3,4]   ,  [-5,6]  ]
a = np.array(a)
b = np.array([1,10])
c = 100
d= np.sum(a*b,axis=1)+c>120

In [15]:
print a
print
print b

[[-1  2]
 [-3  4]
 [-5  6]]

[ 1 10]


In [17]:

d= np.array(d,dtype= int)
print d

[0 1 1]


In [18]:
print np.exp(d)

[ 1.          2.71828183  2.71828183]


In [22]:
e= np.dot(d,a)

In [23]:
print(e)

[-8 10]


$$\Sigma_a\Sigma_bf(a)*f(b)=\Sigma_af(a)*\Sigma_bf(b)$$